# base image
FROM node:16-alpine as node

#########################
### build  ###
#########################

FROM node as builder
#creating & moving to directory
RUN mkdir /app
WORKDIR /app

#copying package
COPY package*.json ./

#Run installation process for dependencies
RUN npm install

#copy all from root to working directory
COPY . .

#run build and prerender for static pages
RUN npm build

#CMD [ "npm", "run", "serve:ssr" ]

###################
#### production ###
###################
FROM node as final

#creating directory and giving full permission to node
RUN mkdir -p /home/app/dist && chown -R node:node /home/app

#changing current working directory
WORKDIR /home/app

#copying packages and env to current directory
COPY package*.json ./
COPY .env ./

##running instalation process only for prod depenfencies
#RUN npm i --only=production

#copying dist folder from the build step and giving full permisssion to node
COPY --chown=node:node --from=builder /app/dist ./dist

EXPOSE 4000

ENTRYPOINT ["node", "dist/devops-gurus/main.js"]



