apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-server
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-image
          image: purbo75/managementfontend
          ports:
            - containerPort: 3000
